# Generated by Django 3.0.5 on 2020-04-10 03:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Updated Timestamp')),
                ('telephone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telephone')),
                ('account', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Account number')),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, verbose_name='Balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Updated Timestamp')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('description', models.CharField(max_length=40, verbose_name='Description')),
                ('holder', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_made', to='holders.Holder', verbose_name='Accuont Holder')),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_received', to='holders.Holder', verbose_name='Accuont Holder')),
            ],
            options={
                'ordering': ['-created_ts'],
            },
        ),
    ]
