# Generated by Django 3.0.5 on 2020-04-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
